# Generated by Django 2.2.3 on 2020-12-08 14:26

from django.db import migrations, models
import imageapp.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ImageModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=imageapp.models.upload_to)),
            ],
        ),
    ]
